
version: 2

jobs:
  build:
    docker:
      - image: cimg/python:3.9.9
      - image: cimg/postgres:16.0
        environment:
          POSTGRES_USER: root

    steps:
      - checkout

      # fleetio note:
      # the section below was written when dbt labs owned the package and supported bigquery and redshift
      # we don't have test environments for redshift and bigquery, but we wanted to keep this in case we can support it in the future
      # we're working on setting up a snowflake service account to use for the snowflake test, but for now we'll only run the CI job for postgres

      # - run:
      #     run: setup_creds
      #     command: |
      #       echo $BIGQUERY_SERVICE_ACCOUNT_JSON > ${HOME}/bigquery-service-key.json
            

      - restore_cache:
          key: deps1-{{ .Branch }}

      - run:
          name: "Setup dbt"
          command: |
            python3 -m venv dbt_venv
            . dbt_venv/bin/activate

            pip install --upgrade pip setuptools
            pip install --pre dbt-core dbt-postgres dbt-snowflake

            mkdir -p ~/.dbt
            cp integration_tests/ci/sample.profiles.yml ~/.dbt/profiles.yml

      - run:
          name: "Run Tests - Postgres"
          environment:
            POSTGRES_TEST_HOST: localhost
            POSTGRES_TEST_USER: root
            POSTGRES_TEST_PASS: ''
            POSTGRES_TEST_PORT: 5432
            POSTGRES_TEST_DBNAME: circle_test
          command: |
            . dbt_venv/bin/activate
            echo `pwd`
            cd integration_tests
            dbt --warn-error deps
            dbt --warn-error seed --target postgres
            dbt --warn-error run --target postgres --full-refresh
            dbt --warn-error run --target postgres

      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files in a dir" > /tmp/artifacts/artifact-2;

      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
      
      # - run:
      #     name: "Run Tests - Redshift"
      #     command: |
      #       . dbt_venv/bin/activate
      #       echo `pwd`
      #       cd integration_tests
      #       dbt --warn-error deps
      #       dbt --warn-error seed --target redshift
      #       dbt --warn-error run --target redshift --full-refresh
      #       dbt --warn-error run --target redshift

      # - run:
      #     name: "Run Tests - BigQuery"
      #     environment:
      #         BIGQUERY_SERVICE_KEY_PATH: "/home/circleci/bigquery-service-key.json"

      #     command: |
      #       . dbt_venv/bin/activate
      #       echo `pwd`
      #       cd integration_tests
      #       dbt --warn-error deps
      #       dbt --warn-error seed --target bigquery
      #       dbt --warn-error run --target bigquery --full-refresh
      #       dbt --warn-error run --target bigquery      


      # - run:
      #     name: "Run Tests - Snowflake"
      #     command: |
      #       . dbt_venv/bin/activate
      #       echo `pwd`
      #       cd integration_tests
      #       dbt --warn-error deps
      #       dbt --warn-error seed --target snowflake
      #       dbt --warn-error run --target snowflake --full-refresh
      #       dbt --warn-error run --target snowflake

      - save_cache:
          key: deps1-{{ .Branch }}
          paths:
            - "dbt_venv"
