version: 2

models:
  - name: segment_web_page_views
    description: "{{doc('segment_web_page_views')}}"
    columns:
      - name: page_view_id
        data_tests:
          - unique
          - not_null
